//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExServiceRequest
    {
        public int Id { get; set; }
        public string B2BFlag { get; set; }
        public string CompletionDate { get; set; }
        public string InputDate { get; set; }
        public string PullingDate { get; set; }
        public string Dealer { get; set; }
        public string DealerName { get; set; }
        public string DealerReceiptNo { get; set; }
        public string ASCRemarks { get; set; }
        public string SchComplaintDate { get; set; }
        public string SchComplaintCount { get; set; }
        public string SchComplaintRemarks { get; set; }
        public string ASCClaimNo { get; set; }
        public string EsnImeiNo { get; set; }
        public string OutModel { get; set; }
        public string ReceiptDate { get; set; }
        public string TransferSendDate { get; set; }
        public string TransferReceiptDate { get; set; }
        public string FirstPromiseDate { get; set; }
        public string Schedule { get; set; }
        public string PromiseDate { get; set; }
        public string Schedule1 { get; set; }
        public string DelayFromPromiseDate { get; set; }
        public string DelayFromReceiptDate { get; set; }
        public string TransferApprovalDate { get; set; }
    
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
