//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TemplateName { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Command { get; set; }
        public bool FilterByDate { get; set; }
        public bool FilterByCustomer { get; set; }
        public bool FilterByDepartment { get; set; }
        public bool FilterByEngineer { get; set; }
        public bool FilterByProduct { get; set; }
        public bool FilterByStatus { get; set; }
        public bool FilterByCity { get; set; }
        public bool FilterByRegion { get; set; }
        public bool FilterByTag { get; set; }
        public bool FilterByText1 { get; set; }
        public bool FilterByText2 { get; set; }
        public bool FilterByNumber1 { get; set; }
        public bool FilterByNumber2 { get; set; }
        public bool FilterByDate1 { get; set; }
        public bool FilterByDate2 { get; set; }
        public string Text1Title { get; set; }
        public string Text2Title { get; set; }
        public string Number1Title { get; set; }
        public string Number2Title { get; set; }
        public string Date1Title { get; set; }
        public string Date2Title { get; set; }
        public bool GVisible { get; set; }
        public string GHeader { get; set; }
        public Nullable<bool> F1Visible { get; set; }
        public string F1Header { get; set; }
        public string F1Map { get; set; }
        public string F1Color { get; set; }
        public string F1Total { get; set; }
        public Nullable<bool> F2Visible { get; set; }
        public string F2Header { get; set; }
        public string F2Map { get; set; }
        public string F2Color { get; set; }
        public string F2Total { get; set; }
        public Nullable<bool> F3Visible { get; set; }
        public string F3Header { get; set; }
        public string F3Map { get; set; }
        public string F3Color { get; set; }
        public string F3Total { get; set; }
        public Nullable<bool> F4Visible { get; set; }
        public string F4Header { get; set; }
        public string F4Map { get; set; }
        public string F4Color { get; set; }
        public string F4Total { get; set; }
        public Nullable<bool> F5Visible { get; set; }
        public string F5Header { get; set; }
        public string F5Map { get; set; }
        public string F5Color { get; set; }
        public string F5Total { get; set; }
        public Nullable<bool> F6Visible { get; set; }
        public string F6Header { get; set; }
        public string F6Map { get; set; }
        public string F6Color { get; set; }
        public string F6Total { get; set; }
        public Nullable<bool> F7Visible { get; set; }
        public string F7Header { get; set; }
        public string F7Map { get; set; }
        public string F7Color { get; set; }
        public string F7Total { get; set; }
        public Nullable<bool> F8Visible { get; set; }
        public string F8Header { get; set; }
        public string F8Map { get; set; }
        public string F8Color { get; set; }
        public string F8Total { get; set; }
    }
}
