CREATE TABLE [dbo].[ExServiceRequests]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [B2BFlag] BIT NULL, 
    [CompletionDate] DATETIME NULL, 
    [InputDate] DATETIME NULL, 
    [PullingDate] DATETIME NULL, 
    [Dealer] NVARCHAR(50) NULL, 
    [DealerName] NVARCHAR(50) NULL, 
    [DealerReceiptNo] NVARCHAR(50) NULL, 
    [ASCRemarks] NVARCHAR(200) NULL, 
    [SchComplaintDate] DATETIME NULL, 
    [SchComplaintCount] INT NULL, 
    [SchComplaintRemarks] NVARCHAR(150) NULL, 
    [ASCClaimNo] NVARCHAR(50) NULL, 
    [EsnImeiNo] NVARCHAR(50) NULL, 
    [OutModel] NVARCHAR(50) NULL, 
    [ReceiptDate] DATETIME NULL, 
    [TransferSendDate] DATETIME NULL, 
    [TransferReceiptDate] DATETIME NULL, 
    [FirstPromiseDate] DATETIME NULL, 
    [Schedule] NVARCHAR(50) NULL, 
    [PromiseDate] DATETIME NULL, 
    [Schedule1] DATETIME NULL, 
    [DelayFromPromiseDate] INT NULL, 
    [DelayFromReceiptDate] INT NULL, 
    [TransferApprovalDate] DATETIME NULL, 
    CONSTRAINT [FK_ExServiceRequests_ToServiceRequests] FOREIGN KEY (Id) REFERENCES [ServiceRequests]([Id])
)
