CREATE TABLE [dbo].[ExServiceRequests]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [B2BFlag] NVARCHAR(MAX) NULL, 
    [CompletionDate] NVARCHAR(MAX) NULL, 
    [InputDate] NVARCHAR(MAX) NULL, 
    [PullingDate] NVARCHAR(MAX) NULL, 
    [Dealer] NVARCHAR(MAX) NULL, 
    [DealerName] NVARCHAR(MAX) NULL, 
    [DealerReceiptNo] NVARCHAR(MAX) NULL, 
    [ASCRemarks] NVARCHAR(MAX) NULL, 
    [SchComplaintDate] NVARCHAR(MAX) NULL, 
    [SchComplaintCount] NVARCHAR(MAX) NULL, 
    [SchComplaintRemarks] NVARCHAR(MAX) NULL, 
    [ASCClaimNo] NVARCHAR(MAX) NULL, 
    [EsnImeiNo] NVARCHAR(MAX) NULL, 
    [OutModel] NVARCHAR(MAX) NULL, 
    [ReceiptDate] NVARCHAR(MAX) NULL, 
    [TransferSendDate] NVARCHAR(MAX) NULL, 
    [TransferReceiptDate] NVARCHAR(MAX) NULL, 
    [FirstPromiseDate] NVARCHAR(MAX) NULL, 
    [Schedule] NVARCHAR(MAX) NULL, 
    [PromiseDate] NVARCHAR(MAX) NULL, 
    [Schedule1] NVARCHAR(MAX) NULL, 
    [DelayFromPromiseDate] NVARCHAR(MAX) NULL, 
    [DelayFromReceiptDate] NVARCHAR(MAX) NULL, 
    [TransferApprovalDate] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_ExServiceRequests_ToServiceRequests] FOREIGN KEY (Id) REFERENCES [ServiceRequests]([Id])
)
