CREATE TABLE [dbo].[Reports]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(50) NOT NULL, 
	[Description] NVARCHAR(200) ,
    [Title] NVARCHAR(100) NOT NULL, 
    [SubTitle] NVARCHAR(100) NULL, 
    [Command] NVARCHAR(MAX) NOT NULL, 
    [FilterByDate] BIT NOT NULL DEFAULT 0, 
    [FilterByCustomer] BIT NOT NULL DEFAULT 0, 
    [FilterByDepartment] BIT NOT NULL DEFAULT 0, 
    [FilterByEngineer] BIT NOT NULL DEFAULT 0, 
    [FilterByProduct] BIT NOT NULL DEFAULT 0, 
    [FilterByStatus] BIT NOT NULL DEFAULT 0, 
    [FilterByCity] BIT NOT NULL DEFAULT 0, 
    [FilterByRegion] BIT NOT NULL DEFAULT 0, 
    [FilterByTag] BIT NOT NULL DEFAULT 0, 
    [FilterByText1] BIT NOT NULL DEFAULT 0, 
    [FilterByText2] BIT NOT NULL DEFAULT 0, 
    [FilterByNumber1] BIT NOT NULL DEFAULT 0, 
    [FilterByNumber2] BIT NOT NULL DEFAULT 0, 
    [FilterByDate1] BIT NOT NULL DEFAULT 0, 
    [FilterByDate2] BIT NOT NULL DEFAULT 0, 
    [Text1Title] NVARCHAR(50) NULL DEFAULT 'Text 1', 
    [Text2Title] NVARCHAR(50) NULL DEFAULT 'Text 2', 
    [Number1Title] NVARCHAR(50) NULL DEFAULT 'Number 1', 
    [Number2Title] NVARCHAR(50) NULL DEFAULT 'Number 2', 
    [Date1Title] NVARCHAR(50) NULL DEFAULT 'Date 1', 
    [Date2Title] NVARCHAR(50) NULL DEFAULT 'Date 2', 
    [GVisible] BIT NOT NULL DEFAULT 0, 
    [GHeader] NVARCHAR(50) NULL DEFAULT 'Group Name', 
    [F1Visible] BIT NULL DEFAULT 0, 
    [F1Header] NVARCHAR(50) NULL DEFAULT 'F1', 
    [F1Map] NVARCHAR(3) NULL DEFAULT 'T1', 
    [F1Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F1Total] NVARCHAR(50) NULL DEFAULT 'Count',
	    [F2Visible] BIT NULL DEFAULT 0, 
    [F2Header] NVARCHAR(50) NULL, 
    [F2Map] NVARCHAR(3) NULL, 
    [F2Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F2Total] NVARCHAR(50) NULL,
	[F3Visible] BIT NULL DEFAULT 0, 
    [F3Header] NVARCHAR(50) NULL, 
    [F3Map] NVARCHAR(3) NULL, 
    [F3Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F3Total] NVARCHAR(50) NULL,
    [F4Visible] BIT NULL DEFAULT 0, 
    [F4Header] NVARCHAR(50) NULL, 
    [F4Map] NVARCHAR(3) NULL, 
    [F4Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F4Total] NVARCHAR(50) NULL,
    [F5Visible] BIT NULL DEFAULT 0, 
    [F5Header] NVARCHAR(50) NULL, 
    [F5Map] NVARCHAR(3) NULL, 
    [F5Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F5Total] NVARCHAR(50) NULL,
    [F6Visible] BIT NULL DEFAULT 0, 
    [F6Header] NVARCHAR(50) NULL, 
    [F6Map] NVARCHAR(3) NULL, 
    [F6Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F6Total] NVARCHAR(50) NULL,
    [F7Visible] BIT NULL DEFAULT 0, 
    [F7Header] NVARCHAR(50) NULL, 
    [F7Map] NVARCHAR(3) NULL, 
    [F7Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F7Total] NVARCHAR(50) NULL,
    [F8Visible] BIT NULL DEFAULT 0, 
    [F8Header] NVARCHAR(50) NULL, 
    [F8Map] NVARCHAR(3) NULL, 
    [F8Color] NVARCHAR(50) NULL DEFAULT 'Black', 
    [F8Total] NVARCHAR(50) NULL
)

GO

CREATE UNIQUE INDEX [IX_Reports_Name] ON [dbo].[Reports] ([Name])
