//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppViews {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppViews() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCM.AppViews", typeof(AppViews).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightweight service call management system.
        /// </summary>
        public static string About_Message {
            get {
                return ResourceManager.GetString("About_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string ActiveRequests {
            get {
                return ResourceManager.GetString("ActiveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllRequests {
            get {
                return ResourceManager.GetString("AllRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCM.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Call Management.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reason.
        /// </summary>
        public static string CancelReason {
            get {
                return ResourceManager.GetString("CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string CancelReason_Id {
            get {
                return ResourceManager.GetString("CancelReason_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string CancelReason_Reason {
            get {
                return ResourceManager.GetString("CancelReason_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reasons.
        /// </summary>
        public static string CancelReasons {
            get {
                return ResourceManager.GetString("CancelReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Center_Code {
            get {
                return ResourceManager.GetString("Center_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Center_Id {
            get {
                return ResourceManager.GetString("Center_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center_Name {
            get {
                return ResourceManager.GetString("Center_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers.
        /// </summary>
        public static string Centers {
            get {
                return ResourceManager.GetString("Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string City_Id {
            get {
                return ResourceManager.GetString("City_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City_Name {
            get {
                return ResourceManager.GetString("City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected region will be removed, do you want to continue?.
        /// </summary>
        public static string CityChangeMsg {
            get {
                return ResourceManager.GetString("CityChangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed.
        /// </summary>
        public static string ClosedRequests {
            get {
                return ResourceManager.GetString("ClosedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Customer_CityId {
            get {
                return ResourceManager.GetString("Customer_CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Customer_Comments {
            get {
                return ResourceManager.GetString("Customer_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Customer_Id {
            get {
                return ResourceManager.GetString("Customer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Customer_IsBlackListed {
            get {
                return ResourceManager.GetString("Customer_IsBlackListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Customer_Mobile {
            get {
                return ResourceManager.GetString("Customer_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Customer_Phone {
            get {
                return ResourceManager.GetString("Customer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Customer_RegionId {
            get {
                return ResourceManager.GetString("Customer_RegionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Customers.
        /// </summary>
        public static string CustomerMerge {
            get {
                return ResourceManager.GetString("CustomerMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer 1.
        /// </summary>
        public static string CustomerMerge_CustomerId1 {
            get {
                return ResourceManager.GetString("CustomerMerge_CustomerId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer 2.
        /// </summary>
        public static string CustomerMerge_CustomerId2 {
            get {
                return ResourceManager.GetString("CustomerMerge_CustomerId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string CustomerTag {
            get {
                return ResourceManager.GetString("CustomerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerTag_CustomerId {
            get {
                return ResourceManager.GetString("CustomerTag_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string CustomerTag_TagId {
            get {
                return ResourceManager.GetString("CustomerTag_TagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string CustomerTags {
            get {
                return ResourceManager.GetString("CustomerTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string DataImport_Done {
            get {
                return ResourceManager.GetString("DataImport_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string DataImport_Import {
            get {
                return ResourceManager.GetString("DataImport_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing master data 1/5.
        /// </summary>
        public static string DataImport_Phase1 {
            get {
                return ResourceManager.GetString("DataImport_Phase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing master data 2/5.
        /// </summary>
        public static string DataImport_Phase2 {
            get {
                return ResourceManager.GetString("DataImport_Phase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing master data 3/5.
        /// </summary>
        public static string DataImport_Phase3 {
            get {
                return ResourceManager.GetString("DataImport_Phase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing master data 4/5.
        /// </summary>
        public static string DataImport_Phase4 {
            get {
                return ResourceManager.GetString("DataImport_Phase4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing master data 5/5.
        /// </summary>
        public static string DataImport_Phase5 {
            get {
                return ResourceManager.GetString("DataImport_Phase5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing customers data.
        /// </summary>
        public static string DataImport_Phase6 {
            get {
                return ResourceManager.GetString("DataImport_Phase6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing requests.
        /// </summary>
        public static string DataImport_Phase7 {
            get {
                return ResourceManager.GetString("DataImport_Phase7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests File.
        /// </summary>
        public static string DataImport_RequestsFile {
            get {
                return ResourceManager.GetString("DataImport_RequestsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string DataImport_Title {
            get {
                return ResourceManager.GetString("DataImport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delayed.
        /// </summary>
        public static string DelayedRequests {
            get {
                return ResourceManager.GetString("DelayedRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Delete_Message {
            get {
                return ResourceManager.GetString("Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Department_Id {
            get {
                return ResourceManager.GetString("Department_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Department_Name {
            get {
                return ResourceManager.GetString("Department_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected product and engineer will be removed, do you want to continue?.
        /// </summary>
        public static string DepartmentChangeMsg {
            get {
                return ResourceManager.GetString("DepartmentChangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Engineer_DepartmentId {
            get {
                return ResourceManager.GetString("Engineer_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Engineer_Id {
            get {
                return ResourceManager.GetString("Engineer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string Engineer_Name {
            get {
                return ResourceManager.GetString("Engineer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Engineer_Phone {
            get {
                return ResourceManager.GetString("Engineer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineers.
        /// </summary>
        public static string Engineers {
            get {
                return ResourceManager.GetString("Engineers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search for.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        public static string Ext {
            get {
                return ResourceManager.GetString("Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC.
        /// </summary>
        public static string Filter_SortAsc {
            get {
                return ResourceManager.GetString("Filter_SortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string Filter_SortBy {
            get {
                return ResourceManager.GetString("Filter_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delay.
        /// </summary>
        public static string Filter_SortByDelay {
            get {
                return ResourceManager.GetString("Filter_SortByDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update date.
        /// </summary>
        public static string Filter_SortByLastUpdate {
            get {
                return ResourceManager.GetString("Filter_SortByLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request date.
        /// </summary>
        public static string Filter_SortByRequestDate {
            get {
                return ResourceManager.GetString("Filter_SortByRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESC.
        /// </summary>
        public static string Filter_SortDesc {
            get {
                return ResourceManager.GetString("Filter_SortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Reload Requests.
        /// </summary>
        public static string ForceReload {
            get {
                return ResourceManager.GetString("ForceReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string PageCreate {
            get {
                return ResourceManager.GetString("PageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PageDelete {
            get {
                return ResourceManager.GetString("PageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string PageDetails {
            get {
                return ResourceManager.GetString("PageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PageEdit {
            get {
                return ResourceManager.GetString("PageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reason.
        /// </summary>
        public static string PendingReason {
            get {
                return ResourceManager.GetString("PendingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string PendingReason_Id {
            get {
                return ResourceManager.GetString("PendingReason_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string PendingReason_Reason {
            get {
                return ResourceManager.GetString("PendingReason_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reasons.
        /// </summary>
        public static string PendingReasons {
            get {
                return ResourceManager.GetString("PendingReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pending.
        /// </summary>
        public static string PendingRequests {
            get {
                return ResourceManager.GetString("PendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string PhoneCall {
            get {
                return ResourceManager.GetString("PhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling No..
        /// </summary>
        public static string PhoneCall_CallingId {
            get {
                return ResourceManager.GetString("PhoneCall_CallingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Time.
        /// </summary>
        public static string PhoneCall_CallTime {
            get {
                return ResourceManager.GetString("PhoneCall_CallTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string PhoneCall_CreatedBy {
            get {
                return ResourceManager.GetString("PhoneCall_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string PhoneCall_CreatedOn {
            get {
                return ResourceManager.GetString("PhoneCall_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string PhoneCall_CustomerId {
            get {
                return ResourceManager.GetString("PhoneCall_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        public static string PhoneCall_Ext {
            get {
                return ResourceManager.GetString("PhoneCall_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string PhoneCall_Id {
            get {
                return ResourceManager.GetString("PhoneCall_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string PhoneCall_Remarks {
            get {
                return ResourceManager.GetString("PhoneCall_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string PhoneCall_ServiceRequestId {
            get {
                return ResourceManager.GetString("PhoneCall_ServiceRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calls.
        /// </summary>
        public static string PhoneCalls {
            get {
                return ResourceManager.GetString("PhoneCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Product_DepartmentId {
            get {
                return ResourceManager.GetString("Product_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Product_Id {
            get {
                return ResourceManager.GetString("Product_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Region_CityId {
            get {
                return ResourceManager.GetString("Region_CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Region_Id {
            get {
                return ResourceManager.GetString("Region_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region_Name {
            get {
                return ResourceManager.GetString("Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string Report_FilterByDate {
            get {
                return ResourceManager.GetString("Report_FilterByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Report_FromDate {
            get {
                return ResourceManager.GetString("Report_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report_Id {
            get {
                return ResourceManager.GetString("Report_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Name.
        /// </summary>
        public static string Report_Name {
            get {
                return ResourceManager.GetString("Report_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        public static string Report_SubTitle {
            get {
                return ResourceManager.GetString("Report_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Report_Title {
            get {
                return ResourceManager.GetString("Report_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Report_ToDate {
            get {
                return ResourceManager.GetString("Report_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested on.
        /// </summary>
        public static string RequestedOn {
            get {
                return ResourceManager.GetString("RequestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Modifier By Department.
        /// </summary>
        public static string RequestsDepartmentMod {
            get {
                return ResourceManager.GetString("RequestsDepartmentMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department 1.
        /// </summary>
        public static string RequestsDepartmentMod_DepartmentId1 {
            get {
                return ResourceManager.GetString("RequestsDepartmentMod_DepartmentId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department 2.
        /// </summary>
        public static string RequestsDepartmentMod_DepartmentId2 {
            get {
                return ResourceManager.GetString("RequestsDepartmentMod_DepartmentId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Department in All Requests.
        /// </summary>
        public static string RequestsDepartmentMod_Update {
            get {
                return ResourceManager.GetString("RequestsDepartmentMod_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Modifier By Engineer.
        /// </summary>
        public static string RequestsEngineerMod {
            get {
                return ResourceManager.GetString("RequestsEngineerMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer 1.
        /// </summary>
        public static string RequestsEngineerMod_EngineerId1 {
            get {
                return ResourceManager.GetString("RequestsEngineerMod_EngineerId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer 2.
        /// </summary>
        public static string RequestsEngineerMod_EngineerId2 {
            get {
                return ResourceManager.GetString("RequestsEngineerMod_EngineerId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Engineer in All Requests.
        /// </summary>
        public static string RequestsEngineerMod_Update {
            get {
                return ResourceManager.GetString("RequestsEngineerMod_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Modifier By Product.
        /// </summary>
        public static string RequestsProductMod {
            get {
                return ResourceManager.GetString("RequestsProductMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product 1.
        /// </summary>
        public static string RequestsProductMod_ProductId1 {
            get {
                return ResourceManager.GetString("RequestsProductMod_ProductId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product 2.
        /// </summary>
        public static string RequestsProductMod_ProductId2 {
            get {
                return ResourceManager.GetString("RequestsProductMod_ProductId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Engineer in All Requests.
        /// </summary>
        public static string RequestsProductMod_Update {
            get {
                return ResourceManager.GetString("RequestsProductMod_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string RequestTag {
            get {
                return ResourceManager.GetString("RequestTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string RequestTag_ServiceRequest_Id {
            get {
                return ResourceManager.GetString("RequestTag_ServiceRequest_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string RequestTag_TagId {
            get {
                return ResourceManager.GetString("RequestTag_TagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string RequestTags {
            get {
                return ResourceManager.GetString("RequestTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string RPT_Requests {
            get {
                return ResourceManager.GetString("RPT_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string ServiceRequest {
            get {
                return ResourceManager.GetString("ServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string ServiceRequests {
            get {
                return ResourceManager.GetString("ServiceRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results for.
        /// </summary>
        public static string ShowResultsFor {
            get {
                return ResourceManager.GetString("ShowResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reason.
        /// </summary>
        public static string SR_CancelReasonId {
            get {
                return ResourceManager.GetString("SR_CancelReasonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string SR_CenterId {
            get {
                return ResourceManager.GetString("SR_CenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Date.
        /// </summary>
        public static string SR_ClosingDate {
            get {
                return ResourceManager.GetString("SR_ClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string SR_CreatedBy {
            get {
                return ResourceManager.GetString("SR_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string SR_CreatedOn {
            get {
                return ResourceManager.GetString("SR_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string SR_CustomerId {
            get {
                return ResourceManager.GetString("SR_CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string SR_DepartmentId {
            get {
                return ResourceManager.GetString("SR_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SR_Description {
            get {
                return ResourceManager.GetString("SR_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string SR_EngineerId {
            get {
                return ResourceManager.GetString("SR_EngineerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SR_Id {
            get {
                return ResourceManager.GetString("SR_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string SR_IsDeleted {
            get {
                return ResourceManager.GetString("SR_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string SR_Model {
            get {
                return ResourceManager.GetString("SR_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Reason.
        /// </summary>
        public static string SR_PendingReasonId {
            get {
                return ResourceManager.GetString("SR_PendingReasonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string SR_ProductId {
            get {
                return ResourceManager.GetString("SR_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string SR_ReceiptNo {
            get {
                return ResourceManager.GetString("SR_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string SR_Remarks {
            get {
                return ResourceManager.GetString("SR_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string SR_RequestDate {
            get {
                return ResourceManager.GetString("SR_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RQN.
        /// </summary>
        public static string SR_RQN {
            get {
                return ResourceManager.GetString("SR_RQN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N.
        /// </summary>
        public static string SR_SN {
            get {
                return ResourceManager.GetString("SR_SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Date.
        /// </summary>
        public static string SR_StatusDate {
            get {
                return ResourceManager.GetString("SR_StatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SR_StatusId {
            get {
                return ResourceManager.GetString("SR_StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        public static string SR_UpdatedBy {
            get {
                return ResourceManager.GetString("SR_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On.
        /// </summary>
        public static string SR_UpdatedOn {
            get {
                return ResourceManager.GetString("SR_UpdatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string StatusCanceled {
            get {
                return ResourceManager.GetString("StatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string StatusClosed {
            get {
                return ResourceManager.GetString("StatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Tag_Format {
            get {
                return ResourceManager.GetString("Tag_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Tag_Id {
            get {
                return ResourceManager.GetString("Tag_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Tag_Name {
            get {
                return ResourceManager.GetString("Tag_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Tag_TagType {
            get {
                return ResourceManager.GetString("Tag_TagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Call.
        /// </summary>
        public static string TakeIn {
            get {
                return ResourceManager.GetString("TakeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canceled on.
        /// </summary>
        public static string TextCanceledOn {
            get {
                return ResourceManager.GetString("TextCanceledOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closed on.
        /// </summary>
        public static string TextClosedOn {
            get {
                return ResourceManager.GetString("TextClosedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requested on.
        /// </summary>
        public static string TextRequestedOn {
            get {
                return ResourceManager.GetString("TextRequestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status on.
        /// </summary>
        public static string TextStatusOn {
            get {
                return ResourceManager.GetString("TextStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
    }
}
