//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExSvc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExSvc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCM.ExSvc", typeof(ExSvc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC Claim No..
        /// </summary>
        public static string ASCClaimNo {
            get {
                return ResourceManager.GetString("ASCClaimNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASC Remarks.
        /// </summary>
        public static string ASCRemarks {
            get {
                return ResourceManager.GetString("ASCRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2B Flag.
        /// </summary>
        public static string B2BFlag {
            get {
                return ResourceManager.GetString("B2BFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Request.
        /// </summary>
        public static string BackToRequest {
            get {
                return ResourceManager.GetString("BackToRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name.
        /// </summary>
        public static string DealerName {
            get {
                return ResourceManager.GetString("DealerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Receipt No.
        /// </summary>
        public static string DealerReceiptNo {
            get {
                return ResourceManager.GetString("DealerReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay From Promise Date.
        /// </summary>
        public static string DelayFromPromiseDate {
            get {
                return ResourceManager.GetString("DelayFromPromiseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay From Receipt Date.
        /// </summary>
        public static string DelayFromReceiptDate {
            get {
                return ResourceManager.GetString("DelayFromReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esn/Imei No..
        /// </summary>
        public static string EsnImeiNo {
            get {
                return ResourceManager.GetString("EsnImeiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext. Request.
        /// </summary>
        public static string ExtRequest {
            get {
                return ResourceManager.GetString("ExtRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext. Service Request.
        /// </summary>
        public static string ExtServiceRequest {
            get {
                return ResourceManager.GetString("ExtServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Promise Date.
        /// </summary>
        public static string FirstPromiseDate {
            get {
                return ResourceManager.GetString("FirstPromiseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Date.
        /// </summary>
        public static string InputDate {
            get {
                return ResourceManager.GetString("InputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Model.
        /// </summary>
        public static string OutModel {
            get {
                return ResourceManager.GetString("OutModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promise Date.
        /// </summary>
        public static string PromiseDate {
            get {
                return ResourceManager.GetString("PromiseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulling Date.
        /// </summary>
        public static string PullingDate {
            get {
                return ResourceManager.GetString("PullingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Date.
        /// </summary>
        public static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Complaint Count.
        /// </summary>
        public static string SchComplaintCount {
            get {
                return ResourceManager.GetString("SchComplaintCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Complaint Date.
        /// </summary>
        public static string SchComplaintDate {
            get {
                return ResourceManager.GetString("SchComplaintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Complaint Remarks.
        /// </summary>
        public static string SchComplaintRemarks {
            get {
                return ResourceManager.GetString("SchComplaintRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule1.
        /// </summary>
        public static string Schedule1 {
            get {
                return ResourceManager.GetString("Schedule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Approval Date.
        /// </summary>
        public static string TransferApprovalDate {
            get {
                return ResourceManager.GetString("TransferApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Receipt Date.
        /// </summary>
        public static string TransferReceiptDate {
            get {
                return ResourceManager.GetString("TransferReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Send Date.
        /// </summary>
        public static string TransferSendDate {
            get {
                return ResourceManager.GetString("TransferSendDate", resourceCulture);
            }
        }
    }
}
